# image: https://hub.docker.com/_/neo4j
# docs: https://neo4j.com/docs/operations-manual/current/docker/introduction/

version: '3.8'
services:

  neo4j:
    container_name: ${APP_NAME}
    image: neo4j:${DB_NEO4J_VERSION}
    environment:
    #   SECURE_FILE_PERMISSIONS=yes
     - NEO4J_AUTH=${DB_NEO4J_USER}/${DB_NEO4J_PASSWORD}
    ports:
     - ${DB_NEO4J_PORT}:7687
     - ${APP_HTTP_PORT}:7474
    restart: always
    volumes:
     - neo4j:/var/lib/neo4j
  
networks:
  default:
    name: ${APP_NETWORK}
    external: true
    
volumes:
  neo4j:
